### ISSUE TITLE
Missing stuff

### ISSUE THREAD

**Issue by bbodine1** [birdduck/atom-sleuth#1]
There is nothing in the repo. ;)

**Comment by crteal** [comment]
It's not ready for primetime yet! If you want to take it for a spin check out the `develop` branch [here](https://github.com/birdduck/atom-sleuth/tree/develop). For the most part I've returned to Vim, so I have no idea if it still works (i.e., your mileage may vary).

**Comment by bbodine1** [comment]
Old ... closing
